n1=(input('Digite algo: '))

print ('='*75)
print (f'O que foi digitado é alfanumerico? {n1.isalnum()}')
print (f'O que foi digitado é feito de letras? {n1.isalpha()}')
print (f'O que foi digitado esta na tabela ASCII (0–127)? {n1.isascii()}')
print (f'O que foi digitado é decimal? {n1.isdecimal()}')
print (f'O que foi digitado é só numeros inteiros? (1-9) {n1.isdigit()}')
print (f'O que foi digitado pode ser o nome de uma variavel? {n1.isidentifier()}')
print (f'O que foi digitado é só numeros? {n1.isnumeric()}')
print (f'O que foi digitado pode ser impresso? {n1.isprintable()}')
print (f'O que foi digitado é só espaço? {n1.isspace()}')
print (f'O que foi digitado esta em minusculo? {n1.islower()}')
print (f'O que foi digitado esta em maiusculo? {n1.isupper()}', end=' ')
print (f'O que foi digitado é  um Titulo? {n1.istitle()}')
print ('='*75)
